BEGIN;
DROP TABLE IF EXISTS payments CASCADE;
DROP TABLE IF EXISTS order_product CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS users CASCADE;
END;


-- BEGIN;
-- DROP TABLE IF EXISTS users CASCADE;
-- END;